---
- hosts: desktop
  become: true
    
- name: Install all needed packages
  apt:
    name: 
      - wget
      - curl 
      - ffmpeg
      - gparted
      - zip 
      - smplayer
      - vlc 
      - ffmpeg
      - gftp
      
    update_cache: yes

  - name: Install latest Google Chrome
    apt:
      deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  
  - name: Install latest Google Earth
    apt:
      deb: https://dl.google.com/linux/direct/google-earth-stable_current_amd64.deb

    - name: Install latest M$ VCode
    apt:
      deb: https://go.microsoft.com/fwlink/?LinkID=760868

  - name: Add Cron task daily update/upgrade
    cron:
      name: Daily upgrade
      user:
      minute: "0 4 * * *"
      job: apt-get update && apt-get upgrade
    
  - name: copy wallpaper file
    copy:
      src: /tmp/AnsibleForDesktop/vista.jpg
      dest: /usr/share/backgrounds/ansible-wallpaper.png
      owner: root
      group: root
  